// ============================================================
// AUTO-GENERATED by dapp-generator.js
// Contract : AcademicCredentials
// Network  : http://127.0.0.1:7545  (Chain ID 1337)
// ============================================================

const CONTRACT_ADDRESS = '0x51EdfF756a2dafA571052F3094c1da28658269C7';

const CONTRACT_ABI = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "credentialHash",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "student",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "university",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "degree",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "field",
        "type": "string"
      }
    ],
    "name": "CredentialIssued",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "credentialHash",
        "type": "bytes32"
      }
    ],
    "name": "CredentialRevoked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "credentialHash",
        "type": "bytes32"
      }
    ],
    "name": "CredentialUnrevoked",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "admin",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_credentialHash",
        "type": "bytes32"
      }
    ],
    "name": "getCredential",
    "outputs": [
      {
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "university",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "degree",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "field",
        "type": "string"
      },
      {
        "internalType": "address",
        "name": "student",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "revoked",
        "type": "bool"
      },
      {
        "internalType": "bool",
        "name": "exists",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_student",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "_name",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_university",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_degree",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_field",
        "type": "string"
      }
    ],
    "name": "issueCredential",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "credentialHash",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_credentialHash",
        "type": "bytes32"
      }
    ],
    "name": "revokeCredential",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_credentialHash",
        "type": "bytes32"
      }
    ],
    "name": "unrevokeCredential",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "_credentialHash",
        "type": "bytes32"
      }
    ],
    "name": "verifyCredential",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
];

// ── State ────────────────────────────────────────────────────
let web3;
let contract;
let currentAccount;

// ── Utilities ────────────────────────────────────────────────

function formatValue(val) {
  if (val === null || val === undefined) return '—';
  if (typeof val === 'object') return JSON.stringify(val);
  return String(val);
}

function showTxResult(fnName, msg, type) {
  const el = document.getElementById('tx_' + fnName);
  if (!el) return;
  el.textContent = msg;
  el.className = 'tx-result ' + type;
}

function logEvent(name, data, blockNum) {
  const log = document.getElementById('eventLog');
  if (!log) return;
  // Remove placeholder
  const placeholder = log.querySelector('p');
  if (placeholder) placeholder.remove();

  const entry = document.createElement('div');
  entry.className = 'log-entry';
  entry.innerHTML = `<span class="ev-name">${name}</span>
    <span class="ev-block">block ${blockNum}</span>
    <pre style="margin-top:4px;font-size:11px;color:#64748b;white-space:pre-wrap">${data}</pre>`;
  log.prepend(entry);
}

function refreshAll() {

}

// ── Wallet connection ─────────────────────────────────────────

async function connectWallet() {
  if (typeof window.ethereum === 'undefined') {
    alert('MetaMask not detected. Please install it from https://metamask.io');
    return;
  }

  web3 = new Web3(window.ethereum);

  try {
    const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' });
    currentAccount = accounts[0];
  } catch (err) {
    alert('Wallet connection rejected.');
    return;
  }

  // Verify correct network
  const chainId = await web3.eth.getChainId();
  const expectedChain = 1337;
  const netEl = document.getElementById('networkDisplay');
  if (chainId !== expectedChain) {
    if (netEl) netEl.textContent = `⚠ Wrong network (chain ${chainId}, expected ${expectedChain})`;
    if (netEl) netEl.style.color = '#f87171';
  } else {
    if (netEl) netEl.textContent = `Chain ID: ${chainId}`;
    if (netEl) netEl.style.color = '#4ade80';
  }

  // Update UI
  const dot = document.getElementById('statusDot');
  const addrEl = document.getElementById('accountDisplay');
  const btn = document.getElementById('connectBtn');
  if (dot) dot.classList.add('connected');
  if (addrEl) addrEl.textContent = currentAccount;
  if (btn)  btn.textContent = 'Connected ✓';

  // Instantiate contract
  contract = new web3.eth.Contract(CONTRACT_ABI, CONTRACT_ADDRESS);

  // Initial read
  refreshAll();

  // Subscribe to events
  
  contract.events.CredentialIssued({}, (err, event) => {
    if (err) return;
    const args = JSON.stringify(event.returnValues, null, 2);
    logEvent('CredentialIssued', args, event.blockNumber);
  });

  contract.events.CredentialRevoked({}, (err, event) => {
    if (err) return;
    const args = JSON.stringify(event.returnValues, null, 2);
    logEvent('CredentialRevoked', args, event.blockNumber);
  });

  contract.events.CredentialUnrevoked({}, (err, event) => {
    if (err) return;
    const args = JSON.stringify(event.returnValues, null, 2);
    logEvent('CredentialUnrevoked', args, event.blockNumber);
  });

  // Handle account change
  window.ethereum.on('accountsChanged', (accounts) => {
    currentAccount = accounts[0] || null;
    if (addrEl) addrEl.textContent = currentAccount || 'Disconnected';
    if (dot) dot.classList.toggle('connected', !!currentAccount);
  });
}

// ── Read functions ────────────────────────────────────────────

async function call_getCredential() {
  if (!contract) { showTxResult('getCredential', 'Connect wallet first', 'error'); return; }
  showTxResult('getCredential', 'Querying...', 'info');

  const raw__credentialHash = document.getElementById('input_getCredential__credentialHash')?.value?.trim();
  if (raw__credentialHash === '' || raw__credentialHash === undefined) { showTxResult('getCredential', 'Input "_credentialHash" is required', 'error'); return; }
  let arg__credentialHash = raw__credentialHash;
  if (arg__credentialHash.length < 66) arg__credentialHash = arg__credentialHash.padEnd(66, '0');
  try {
    const result = await contract.methods.getCredential(arg__credentialHash).call();
    
    const el_0 = document.getElementById('out_getCredential_0');
    if (el_0) el_0.textContent = formatValue(result[0]);
    const el_1 = document.getElementById('out_getCredential_1');
    if (el_1) el_1.textContent = formatValue(result[1]);
    const el_2 = document.getElementById('out_getCredential_2');
    if (el_2) el_2.textContent = formatValue(result[2]);
    const el_3 = document.getElementById('out_getCredential_3');
    if (el_3) el_3.textContent = formatValue(result[3]);
    const el_4 = document.getElementById('out_getCredential_4');
    if (el_4) el_4.textContent = formatValue(result[4]);
    const el_5 = document.getElementById('out_getCredential_5');
    if (el_5) el_5.textContent = formatValue(result[5]);
    const el_6 = document.getElementById('out_getCredential_6');
    if (el_6) el_6.textContent = formatValue(result[6]);
    showTxResult('getCredential', '✅ Success', 'ok');
  } catch (err) {
    console.error('getCredential error:', err);
    showTxResult('getCredential', '❌ Error: ' + (err.message || err), 'error');
  }
}

async function call_verifyCredential() {
  if (!contract) { showTxResult('verifyCredential', 'Connect wallet first', 'error'); return; }
  showTxResult('verifyCredential', 'Querying...', 'info');

  const raw__credentialHash = document.getElementById('input_verifyCredential__credentialHash')?.value?.trim();
  if (raw__credentialHash === '' || raw__credentialHash === undefined) { showTxResult('verifyCredential', 'Input "_credentialHash" is required', 'error'); return; }
  let arg__credentialHash = raw__credentialHash;
  if (arg__credentialHash.length < 66) arg__credentialHash = arg__credentialHash.padEnd(66, '0');
  try {
    const result = await contract.methods.verifyCredential(arg__credentialHash).call();
    
    const el_0 = document.getElementById('out_verifyCredential_0');
    if (el_0) el_0.textContent = formatValue(result);
    showTxResult('verifyCredential', '✅ Success', 'ok');
  } catch (err) {
    console.error('verifyCredential error:', err);
    showTxResult('verifyCredential', '❌ Error: ' + (err.message || err), 'error');
  }
}

// ── Write functions ───────────────────────────────────────────

async function send_issueCredential() {
  if (!contract) { alert('Connect wallet first'); return; }
  showTxResult('issueCredential', 'Waiting for MetaMask confirmation…', 'info');
  
  const raw__student = document.getElementById('input_issueCredential__student')?.value?.trim();
  if (raw__student === '' || raw__student === undefined) { showTxResult('issueCredential', 'Input "_student" is required', 'error'); return; }
  let arg__student = raw__student;
  const raw__name = document.getElementById('input_issueCredential__name')?.value?.trim();
  if (raw__name === '' || raw__name === undefined) { showTxResult('issueCredential', 'Input "_name" is required', 'error'); return; }
  let arg__name = raw__name;
  const raw__university = document.getElementById('input_issueCredential__university')?.value?.trim();
  if (raw__university === '' || raw__university === undefined) { showTxResult('issueCredential', 'Input "_university" is required', 'error'); return; }
  let arg__university = raw__university;
  const raw__degree = document.getElementById('input_issueCredential__degree')?.value?.trim();
  if (raw__degree === '' || raw__degree === undefined) { showTxResult('issueCredential', 'Input "_degree" is required', 'error'); return; }
  let arg__degree = raw__degree;
  const raw__field = document.getElementById('input_issueCredential__field')?.value?.trim();
  if (raw__field === '' || raw__field === undefined) { showTxResult('issueCredential', 'Input "_field" is required', 'error'); return; }
  let arg__field = raw__field;
  try {
    const tx = await contract.methods.issueCredential(arg__student, arg__name, arg__university, arg__degree, arg__field).send({ from: currentAccount });
    showTxResult('issueCredential', '✅ Confirmed: ' + tx.transactionHash, 'ok');
    refreshAll();
    logEvent('issueCredential (tx)', tx.transactionHash, tx.blockNumber);
  } catch (err) {
    showTxResult('issueCredential', '❌ ' + (err.message || err), 'error');
  }
}

async function send_revokeCredential() {
  if (!contract) { alert('Connect wallet first'); return; }
  showTxResult('revokeCredential', 'Waiting for MetaMask confirmation…', 'info');
  
  const raw__credentialHash = document.getElementById('input_revokeCredential__credentialHash')?.value?.trim();
  if (raw__credentialHash === '' || raw__credentialHash === undefined) { showTxResult('revokeCredential', 'Input "_credentialHash" is required', 'error'); return; }
  let arg__credentialHash = raw__credentialHash;
  if (arg__credentialHash.length < 66) arg__credentialHash = arg__credentialHash.padEnd(66, '0');
  try {
    const tx = await contract.methods.revokeCredential(arg__credentialHash).send({ from: currentAccount });
    showTxResult('revokeCredential', '✅ Confirmed: ' + tx.transactionHash, 'ok');
    refreshAll();
    logEvent('revokeCredential (tx)', tx.transactionHash, tx.blockNumber);
  } catch (err) {
    showTxResult('revokeCredential', '❌ ' + (err.message || err), 'error');
  }
}

async function send_unrevokeCredential() {
  if (!contract) { alert('Connect wallet first'); return; }
  showTxResult('unrevokeCredential', 'Waiting for MetaMask confirmation…', 'info');
  
  const raw__credentialHash = document.getElementById('input_unrevokeCredential__credentialHash')?.value?.trim();
  if (raw__credentialHash === '' || raw__credentialHash === undefined) { showTxResult('unrevokeCredential', 'Input "_credentialHash" is required', 'error'); return; }
  let arg__credentialHash = raw__credentialHash;
  if (arg__credentialHash.length < 66) arg__credentialHash = arg__credentialHash.padEnd(66, '0');
  try {
    const tx = await contract.methods.unrevokeCredential(arg__credentialHash).send({ from: currentAccount });
    showTxResult('unrevokeCredential', '✅ Confirmed: ' + tx.transactionHash, 'ok');
    refreshAll();
    logEvent('unrevokeCredential (tx)', tx.transactionHash, tx.blockNumber);
  } catch (err) {
    showTxResult('unrevokeCredential', '❌ ' + (err.message || err), 'error');
  }
}

// ── Auto-connect on load ──────────────────────────────────────
window.addEventListener('load', () => {
  if (typeof window.ethereum !== 'undefined' && window.ethereum.selectedAddress) {
    connectWallet();
  }
});
